# directors --------------------------->
insert into directors values (1,'2023-05-05','2023-05-05',true,57,'James Gunn was born and raised in St. Louis, Missouri, to Leota and James Francis Gunn. He is from a large Catholic family, with Irish and Czech ancestry. His father and his uncles were all lawyers. He has been writing and performing as long as he can remember. He began making 8mm films at the age of twelve. Many of these were comedic splatter films featuring his brothers being disemboweled by zombies. He attended Saint Louis University High (SLUH) college preparatory school but later dropped out of college to pursue a rock and roll career.

His band, "the Icons", released one album, "Mom, We Like It Here on Earth". He earned very little money doing this and so during this time, he also worked as an orderly in Tucson, Arizona, upon which many of the situations in his first novel, "The Toy Collector", are based. He wrote and drew comic strips for underground and college newspapers.

Gunn eventually returned to school and received his B.A. at Saint Louis University in his native St. Louis. He moved to New York where he received an MFA in creative writing from Columbia University, which he today thinks may have been a wonderfully expensive waste of time. While finishing his MFA, he started writing "The Toy Collector" and began working for "Troma Studios", America''s leading B-Movie production company. While there he wrote and produced the cult classic Тромео и Джульетта (1996) and, with Lloyd Kaufman, he wrote "All I Need to Know about Filmmaking I Learned from the Toxic Avenger".

Gunn had a spiritual awakening in Cannes in 1997 and quit Troma and relocated from New York to Los Angeles. He wrote and acted in the film Необыкновенные (2000) with Rob Lowe, Jamie Kennedy, Thomas J. Churchill and his brother Sean Gunn. He wrote two scripts for Warner Brothers live action movies: Spy vs. Spy (1985) and Скуби-Ду (2002). In 1999, after almost five years, he finished "The Toy Collector". After doing Скуби-Ду 2: Монстры на свободе (2004), Gunn made his directorial debut with Слизняк (2006). He later made the superhero film Супер (2010) and the successful Marvel films Стражи Галактики (2014) and its sequel Стражи Галактики. Часть 2 (2017)

Gunn has four brothers, all of whom are in the entertainment industry. His brother, Patrick Gunn, is a Senior VP at Artisan Entertainment, the company responsible for distributing (and the marketing campaign of) Ведьма из Блэр: Курсовая с того света (1999). His brother, Brian Gunn, is a screenwriter who works in partnership with their cousin Mark Gunn.

Gunn''s brother, Matt Gunn wrote and starred in the winner of the 1997 Sundance Film Festival, Man About Town (1997). Gunn''s brother, Sean Gunn, is an actor regularly seen in films, commercials, and such TV shows as Ангел (1999). James and Sean have collaborated on two occasions Sean starred in Тромео и Джульетта (1996), and they acted together and co-produced Необыкновенные (2000). The brothers have one sister, Beth, who is a lawyer.

Gunn married actress and cartoonist Jenna Fischer in 2000. They divorced in 2008. He is now in a relationship with Jennifer Holland','James','MALE','https://www.hollywoodreporter.com/wp-content/uploads/2021/08/James-Gunn-GettyImages-1332063503-H-2021.jpg?w=1296','Gunn');
insert into directors values (2,'2023-05-05','2023-05-05',true,53,'Best known for his cerebral, often nonlinear, storytelling, acclaimed writer-director Christopher Nolan was born on July 30, 1970, in London, England. Over the course of 15 years of filmmaking, Nolan has gone from low-budget independent films to working on some of the biggest blockbusters ever made.

At 7 years old, Nolan began making short movies with his father''s Super-8 camera. While studying English Literature at University College London, he shot 16-millimeter films at U.C.L.''s film society, where he learned the guerrilla techniques he would later use to make his first feature, Преследование (1998), on a budget of around $6,000. The noir thriller was recognized at a number of international film festivals prior to its theatrical release and gained Nolan enough credibility that he was able to gather substantial financing for his next film.

Nolan''s second film was Помни (2000), which he directed from his own screenplay based on a short story by his brother Jonathan. Starring Guy Pearce, the film brought Nolan numerous honors, including Academy Award and Golden Globe Award nominations for Best Original Screenplay. Nolan went on to direct the critically acclaimed psychological thriller, Бессонница (2002), starring Al Pacino, Robin Williams and Hilary Swank.

The turning point in Nolan''s career occurred when he was awarded the chance to revive the Batman franchise in 2005. In Batman (2005), Nolan brought a level of gravitas back to the iconic hero, and his gritty, modern interpretation was greeted with praise from fans and critics alike. Before moving on to a Batman sequel, Nolan directed, co-wrote, and produced the mystery thriller Престиж (2006), starring Christian Bale and Hugh Jackman as magicians whose obsessive rivalry leads to tragedy and murder.

In 2008, Nolan directed, co-wrote, and produced Dark Knight (2008) which went on to gross more than a billion dollars at the worldwide box office. Nolan was nominated for a Directors Guild of America (D.G.A.) Award, Writers Guild of America (W.G.A.) Award and Producers Guild of America (P.G.A.) Award, and the film also received eight Academy Award nominations.

In 2010, Nolan captivated audiences with the sci-fi thriller Inception (2010), which he directed and produced from his own original screenplay. The thought-provoking drama was a worldwide blockbuster, earning more than $800,000,000 and becoming one of the most discussed and debated films of the year. Among its many honors, Inception received four Academy Awards and eight nominations, including Best Picture and Best Screenplay. Nolan was recognized by his peers with D.G.A. and P.G.A. Award nominations, as well as a W.G.A. Award for his work on the film.','Christopher','MALE','https://upload.wikimedia.org/wikipedia/commons/9/95/Christopher_Nolan_Cannes_2018.jpg','Nolan');
insert into directors values (3,'2023-05-05','2023-05-05',true,60,'Quentin Jerome Tarantino was born in Knoxville, Tennessee. His father, Tony Tarantino, is an Italian-American actor and musician from New York, and his mother, Connie (McHugh), is a nurse from Tennessee. Quentin moved with his mother to Torrance, California, when he was four years old.

In January of 1992, first-time writer-director Tarantino Бешеные псы (1992) appeared at the Sundance Film Festival. The film garnered critical acclaim and the director became a legend immediately. Two years later, he followed up Dogs success with Криминальное чтиво (1994) which premiered at the Cannes film festival, winning the coveted Palme D''Or Award. At the 1995 Academy Awards, it was nominated for the best picture, best director and best original screenplay. Tarantino and writing partner Roger Avary came away with the award only for best original screenplay. In 1995, Tarantino directed one fourth of the anthology Четыре комнаты (1995) with friends and fellow auteurs Alexandre Rockwell, Robert Rodriguez and Allison Anders. The film opened December 25 in the United States to very weak reviews. Tarantino''s next film was От заката до рассвета (1996), a vampire/crime story which he wrote and co-starred with George Clooney. The film did fairly well theatrically.

Since then, Tarantino has helmed several critically and financially successful films, including Джеки Браун (1997), Убить Билла (2003), Убить Билла 2 (2004), Бесславные ублюдки (2009), Джанго освобожденный (2012) and Омерзительная восьмерка (2015).','Quentin','MALE','https://www.themoviedb.org/t/p/w500/1gjcpAa99FAOWGnrUvHEXXsRs7o.jpg','Tarantino');
insert into directors values (4,'2023-05-05','2023-05-05',true,61,'David Fincher was born in 1962 in Denver, Colorado, and was raised in Marin County, California. When he was 18 years old he went to work for John Korty at Korty Films in Mill Valley. He subsequently worked at ILM (Industrial Light and Magic) from 1981-1983. Fincher left ILM to direct TV commercials and music videos after signing with N. Lee Lacy in Hollywood. He went on to found Propaganda in 1987 with fellow directors Dominic Sena, Greg Gold and Nigel Dick. Fincher has directed TV commercials for clients that include Nike, Coca-Cola, Budweiser, Heineken, Pepsi, Levi''s, Converse, AT&T and Chanel. He has directed music videos for Madonna, Sting, The Rolling Stones, Michael Jackson, Aerosmith, George Michael, Iggy Pop, The Wallflowers, Billy Idol, Steve Winwood, The Motels and, most recently, A Perfect Circle.','David','MALE','https://www.film.ru/sites/default/files/people/1466092-1119130.jpg','Fincher');
insert into directors values (5,'2023-05-05','2023-05-05',true,81,'Martin Charles Scorsese was born on November 17, 1942 in Queens, New York City, to Catherine Scorsese (née Cappa) and Charles Scorsese, who both worked in Manhattan''s garment district, and whose families both came from Palermo, Sicily. He was raised in the neighborhood of Little Italy, which later provided the inspiration for several of his films. Scorsese earned a B.S. degree in film communications in 1964, followed by an M.A. in the same field in 1966 at New York University''s School of Film. During this time, he made numerous prize-winning short films including Бритье по-крупному (1967), and directed his first feature film, Кто стучится в дверь ко мне? (1967).

He served as assistant director and an editor of the documentary Вудсток (1970) and won critical and popular acclaim for Злые улицы (1973), which first paired him with actor and frequent collaborator Robert De Niro. In 1976, Scorsese''s Таксист (1976), also starring De Niro, was awarded the Palme d''Or at the Cannes Film Festival, and he followed that film with Нью-Йорк, Нью-Йорк (1977) and Последний вальс (1978). Scorsese directed De Niro to an Oscar-winning performance as boxer Jake LaMotta in Бешеный бык (1980), which received eight Academy Award nominations, including Best Picture and Best Director, and is hailed as one of the masterpieces of modern cinema. Scorsese went on to direct Цвет денег (1986), Последнее искушение Христа (1988), Славные парни (1990), Мыс страха (1991), Эпоха невинности (1993), Казино (1995) and Кундун (1997), among other films. Commissioned by the British Film Institute to celebrate the 100th anniversary of the birth of cinema, Scorsese completed the four-hour documentary, История американского кино от Мартина Скорсезе (1995), co-directed by Michael Henry Wilson.','Martin','MALE','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT76oa2UE7FTEyX889Q_aa7T9rG7BBPnZa7HQ&usqp=CAU','Scorsese');

# movies ---------------------------------->
insert into movies values(4,'2022-11-11','2022-11-11',true, 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.','2:28','https://images.prom.ua/4222523998_w640_h640_4222523998.jpg','tt1375666', 2010, 'Inception', 'Qwe6qXFTdgc', 2);
insert into movies values (1,'2023-05-05','2023-05-05',true,'Still reeling from the loss of Gamora, Peter Quill rallies his team to defend the universe and one of their own - a mission that could mean the end of the Guardians if not successful.','2:30','https://m.media-amazon.com/images/M/MV5BMDgxOTdjMzYtZGQxMS00ZTAzLWI4Y2UtMTQzN2VlYjYyZWRiXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg','tt6791350',2023,'Guardians of the Galaxy Volume 3','JqcncLPi9zw',1);
insert into movies values (2,'2023-05-05','2023-05-05',true,'Supervillains Harley Quinn, Bloodsport, Peacemaker, and a collection of nutty cons at Belle Reve prison join the super-secret, super-shady Task Force X as they are dropped off at the remote, enemy-infused island of Corto Maltese.','2:12','https://www.nwpb.org/wp-content/uploads/2021/08/228803.jpg','tt6334354',2021,'The Suicide Squad','eg5ciqQzmK0',1);
insert into movies values (3,'2023-05-05','2023-05-05',true,'A team of explorers travel through a wormhole in space in an attempt to ensure humanity survival.','2:49','https://m.media-amazon.com/images/I/81kz06oSUeL.jpg','tt0816692',2014,'Interstellar','zSWdZVtXT7E',2);
insert into movies values(5,'2022-11-11','2022-11-11',true, 'After a tragic accident, two stage magicians in 1890s London engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.','2:10','https://www.hdclub.ua/files/film/big/bigi4c8d6065076fc.jpg','tt0482571', 2006, 'The Prestige', 'ELq7V8vkekI', 2);
insert into movies values(6,'2022-11-11','2022-11-11',true, 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.','2:32','https://originalvintagemovieposters.com/wp-content/uploads/2020/03/Dark-Knight-70822-scaled.jpg','tt0468569', 2008, 'The Dark Knight', 'TQfATDZY5Y4', 2);
insert into movies values(7,'2022-11-11','2022-11-11',true, 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.','2:34','https://www.themoviedb.org/t/p/original/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg','tt0110912', 1994, 'Pulp Fiction', '5ZAhzsi1ybM', 3);
insert into movies values(8,'2022-11-11','2022-11-11',true, 'In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owner''s vengeful plans for the same.','2:33','https://m.media-amazon.com/images/I/61PXdxTJGPL.jpg','tt0361748', 2009, 'Inglourious Basterds', 'KnrRy6kSFF0', 3);
insert into movies values(9,'2022-11-11','2022-11-11',true, 'With the help of a German bounty-hunter, a freed slave sets out to rescue his wife from a brutal plantation owner in Mississippi.','2:45','https://m.media-amazon.com/images/M/MV5BMjIyNTQ5NjQ1OV5BMl5BanBnXkFtZTcwODg1MDU4OA@@._V1_.jpg','tt1853728', 2012, 'Django Unchained', '0fUCuvNlOCg', 3);
insert into movies values(10,'2022-11-11','2022-11-11',true, 'In the dead of a Wyoming winter, a bounty hunter and his prisoner find shelter in a cabin currently inhabited by a collection of nefarious characters.','2:48','https://i.ebayimg.com/images/g/bgwAAOSwjMtenKbE/s-l1600.jpg','tt3460252', 2015, 'The Hateful Eight', 'nIOmotayDMY', 3);
insert into movies values(11,'2022-11-11','2022-11-11',true, 'Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.','2:07','https://i.ebayimg.com/images/g/HCQAAOSw~xlasY4~/s-l1600.jpg','tt0114369', 1995, 'Se7en', 'znmZoVkCjpI', 4);
insert into movies values(12,'2022-11-11','2022-11-11',true, 'An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.','2:19','https://cdn.shopify.com/s/files/1/0681/6022/5547/products/2523EBBF-A753-4785-B3AC-41DEAF5E87BA.jpg?v=1674860807','tt0137523', 1999, 'Fight Club', 'qtRKdVHc-cE', 4);
insert into movies values(13,'2022-11-11','2022-11-11',true, 'With his wife''s disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it''s suspected that he may not be innocent.','2:29','https://www.themoviedb.org/t/p/original/qymaJhucquUwjpb8oiqynMeXnID.jpg','tt2267998', 2014, 'Gone Girl', '2-_-1nJf8Vg', 4);
insert into movies values(14,'2022-11-11','2022-11-11',true, 'In 1862, Amsterdam Vallon returns to the Five Points area of New York City seeking revenge against Bill the Butcher, his father''s killer.','2:47','https://m.media-amazon.com/images/M/MV5BNDg3MmI1ZDYtMDZjYi00ZWRlLTk4NzEtZjY4Y2U0NjE5YmRiXkEyXkFqcGdeQXVyNzAxMjE1NDg@._V1_.jpg','tt0217505', 2002, 'Gangs of New York', 'UYsS_3zdwmA', 5);
insert into movies values(15,'2022-11-11','2022-11-11',true, 'An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.','2:31','https://m.media-amazon.com/images/I/51ysmjUAA2L._AC_UF894,1000_QL80_.jpg','tt0407887', 2006, 'The Departed', 'iQpb1LoeVUc', 5);
insert into movies values(16,'2022-11-11','2022-11-11',true, 'Teddy Daniels and Chuck Aule, two US marshals, are sent to an asylum on a remote island in order to investigate the disappearance of a patient, where Teddy uncovers a shocking truth about the place.','2:18','https://m.media-amazon.com/images/M/MV5BYzhiNDkyNzktNTZmYS00ZTBkLTk2MDAtM2U0YjU1MzgxZjgzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg','tt1130884', 2010, 'Shutter Island', 'v8yrZSkKxTA', 5);
insert into movies values(17,'2022-11-11','2022-11-11',true, 'Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker living the high life to his fall involving crime, corruption and the federal government.','3:00','https://m.media-amazon.com/images/M/MV5BMjIxMjgxNTk0MF5BMl5BanBnXkFtZTgwNjIyOTg2MDE@._V1_.jpg','tt0993846', 2013, 'The Wolf of Wall Street', 'iszwuX1AK6A', 5);

# actors ---------------------------------->
insert into actors values (default, '2023-05-09', '2023-05-09', true, 44,'Christopher Michael "Chris" Pratt was born on June 21, 1979 in Virginia, Minnesota and raised in Lake Stevens, Washington, to Kathleen Louise (Indahl), who worked at a supermarket, and Daniel Clifton Pratt, who remodeled houses. He is of mostly Norwegian descent. He graduated from Lake Stevens High School in 1997, and has two older siblings, Cully and Angie.

Chris came to prominence for his small-screen roles, including Bright Abbott in Любовь вдовца (2002), Ché in Однажды в Калифорнии (2003), and Andy Dwyer and Парки и зоны отдыха (2009), and notable film roles in Человек, который изменил всё (2011), Немножко женаты (2012), Цель номер один (2012), Отец-молодец (2013), and Она (2013). In 2014, he broke out as a leading man after headlining two of the year''s biggest films: he voiced Emmet Brickowski in Лего. Фильм (2014) & starred as Peter Quill/Star-Lord in Стражи Галактики (2014). In 2015, he headlined the sci-fi thriller Мир Юрского периода (2015), the fourth installment in the Jurassic Park franchise and his most financially successful film. In 2016, he co-starred in the remake Великолепная семерка (2016), with Denzel Washington and Ethan Hawke, and appeared with Jennifer Lawrence in the sci-fi drama Пассажиры (2016). In the near future, he returns as Star-Lord for Стражи Галактики. Часть 2 (2017), with Мир Юрского периода 2 (2018) not far behind.','Christopher','MALE','https://bignamebio.com/wp-content/uploads/2022/11/chris-pratt-1.jpg','Pratt');
insert into actors values (default, '2023-05-09', '2023-05-09', true, 54,'David Michael Bautista, Jr. was born on January 18, 1969 in Washington, D.C., to Donna Raye (Mullins) and David Michael Bautista, a hairdresser. He has Filipino and Greek ancestry.

When WCW officials told him he''d never make it in sports entertainment, Bautista pushed himself to achieve his dream of being a Superstar. In May 2002, he made his debut on SmackDown using the ring name Batista, but it wasn''t until a move to Raw and two victories over Kane that "The Animal" began to make noise in the WWE Universe. The wins impressed Ric Flair and Triple H, who were looking to align themselves with the industry''s brightest new stars. After a lengthy search, they identified Randy Orton and Batista. Collectively the four Superstars became known as Evolution.

Batista earned his first championship alongside "The Nature Boy" when the duo captured the WWE Tag Team Championships in December 2003. As Evolution dominated WWE, Batista started to emerge from the shadows of Triple H and Ric Flair. By the time Batista won the 2005 Royal Rumble Match, World Heavyweight Champion Triple H viewed him as a serious threat to his title.','David','MALE','https://static.wikia.nocookie.net/marvelcinematicuniverse/images/7/77/Dave_Bautista.jpg/revision/latest?cb=20180424104402','Bautista');
insert into actors values (default, '2023-05-09', '2023-05-09', true, 32,'Margot Elise Robbie was born on July 2, 1990 in Dalby, Queensland, Australia to Scottish parents. Her mother, Sarie Kessler, is a physiotherapist, and her father, is Doug Robbie. She comes from a family of four children, having two brothers and one sister. She graduated from Somerset College in Mudgeeraba, Queensland, Australia, a suburb in the Gold Coast hinterland of South East Queensland, where she and her siblings were raised by their mother and spent much of her time at the farm belonging to her grandparents. In her late teens, she moved to Melbourne, Victoria, Australia to pursue an acting career.','Margot','FEMALE','https://cdn.britannica.com/32/201632-050-66971649/actress-Margot-Robbie-Australian-2018.jpg','Robbie');
insert into actors values (default, '2023-05-09', '2023-05-09', true, 50,'An only child, Idrissa Akuna Elba was born and raised in London, England. His father, Winston, is from Sierra Leone and worked at Ford Dagenham; his mother, Eve, is from Ghana and had a clerical duty. Idris attended school in Canning Town, where he first became involved in acting, before he dropped out. He gained a place in the National Youth Music Theatre - thanks to a £1,500 Prince''s Trust grant. To support himself between acting roles, he worked in jobs such as tyre-fitting, cold call advertising sales, and working night shifts at Ford Dagenham. He worked in nightclubs under the nickname DJ Big Driis at age 19, but began auditioning for television roles in his early-twenties.','Idrissa','MALE','https://i0.wp.com/short-biography.com/wp-content/uploads/idris-elba/Idris-Elba-1024x707.jpg?resize=1024%2C707&ssl=1','Elba');
insert into actors values (default, '2023-05-09', '2023-05-09', true, 52,'American actor and producer Matthew David McConaughey was born in Uvalde, Texas. His mother, Mary Kathleen (McCabe), is a substitute school teacher originally from New Jersey. His father, James Donald McConaughey, was a Mississippi-born gas station owner who ran an oil pipe supply business. He is of Irish, Scottish, German, English, and Swedish descent. Matthew grew up in Longview, Texas, where he graduated from the local High School (1988). Showing little interest in his father''s oil business, which his two brothers later joined, Matthew was longing for a change of scenery, and spent a year in Australia, washing dishes and shoveling chicken manure. Back to the States, he attended the University of Texas in Austin, originally wishing to be a lawyer. But, when he discovered an inspirational Og Mandino book "The Greatest Salesman in the World" before one of his final exams, he suddenly knew he had to change his major from law to film.','Matthew ','MALE','https://m.media-amazon.com/images/M/MV5BMTg0MDc3ODUwOV5BMl5BanBnXkFtZTcwMTk2NjY4Nw@@._V1_FMjpg_UX1000_.jpg','McConaughey');
insert into actors values (default, '2023-05-09', '2023-05-09', true, 46,'Jessica Michelle Chastain was born in Sacramento, California, and was raised in a middle-class household in a Northern California suburb. Her mother, Jerri Chastain, is a vegan chef whose family is originally from Kansas, and her stepfather is a fireman. She discovered dance at the age of nine and was in a dance troupe by age thirteen. She began performing in Shakespearean productions all over the Bay area.

An actor in a production of "Romeo & Juliet" encouraged her to audition for Juilliard as a drama major. She became a member of "Crew 32" with the help of a scholarship from one of the school''s famous alumni, Robin Williams.

In her last year at Juilliard, she was offered a holding deal with TV writer/producer John Wells and she eventually worked in three of his TV shows. Jessica continues to do theatre, having played in "The Cherry Orchard", "Rodney''s Wife", "Salome" and "Othello". She spends her time between New York and Los Angeles, working in theater, film and TV.','Jessica','FEMALE','https://media.cntraveller.com/photos/611bf474042ccafe9a9ae92e/4:3/w_1704,h_1278,c_limit/jessica-chastain-conde-nast-traveller-5march15-rex_1.jpg','Chastain');
insert into actors values (default, '2023-05-09', '2023-05-09', true, 50,'Few actors in the world have had a career quite as diverse as Leonardo DiCaprio''s. DiCaprio has gone from relatively humble beginnings, as a supporting cast member of the sitcom Проблемы роста (1985) and low budget horror movies, such as Зубастики 3 (1991), to a major teenage heartthrob in the 1990s, as the hunky lead actor in movies such as Ромео + Джульетта (1996) and Титаник (1997), to then become a leading man in Hollywood blockbusters, made by internationally renowned directors such as Martin Scorsese and Christopher Nolan.

Leonardo Wilhelm DiCaprio was born November 11, 1974 in Los Angeles, California, the only child of Irmelin DiCaprio (née Indenbirken) and former comic book artist George DiCaprio. His father is of Italian and German descent, and his mother, who is German-born, is of German and Russian ancestry. His middle name, "Wilhelm", was his maternal grandfather''s first name. Leonardo''s father had achieved minor status as an artist and distributor of cult comic book titles, and was even depicted in several issues of American Splendor, the cult semi-autobiographical comic book series by the late ''Harvey Pekar'', a friend of George''s. Leonardo''s performance skills became obvious to his parents early on, and after signing him up with a talent agent who wanted Leonardo to perform under the stage name "Lenny Williams", DiCaprio began appearing on a number of television commercials and educational programs.

DiCaprio began attracting the attention of producers, who cast him in small roles in a number of television series, such as Розанна (1988) and The New Lassie (1989), but it wasn''t until 1991 that DiCaprio made his film debut in Зубастики 3 (1991), a low-budget horror movie. While Зубастики 3 (1991) did little to help showcase DiCaprio''s acting abilities, it did help him develop his show-reel, and attract the attention of the people behind the hit sitcom Проблемы роста (1985), in which Leonardo was cast in the "Cousin Oliver" role of a young homeless boy who moves in with the Seavers. While DiCaprio''s stint on Проблемы роста (1985) was very short, as the sitcom was axed the year after he joined, it helped bring DiCaprio into the public''s attention and, after the sitcom ended, DiCaprio began auditioning for roles in which he would get the chance to prove his acting chops.

Leonardo took up a diverse range of roles in the early 1990s, including a mentally challenged youth in Что гложет Гилберта Грейпа (1993), a young gunslinger in Быстрый и мёртвый (1995) and a drug addict in one of his most challenging roles to date, Jim Carroll in Дневник баскетболиста (1995), a role which the late River Phoenix originally expressed interest in. While these diverse roles helped establish Leonardo''s reputation as an actor, it wasn''t until his role as Romeo Montague in Baz Luhrmann''s Ромео + Джульетта (1996) that Leonardo became a household name, a true movie star. The following year, DiCaprio starred in another movie about doomed lovers, Титаник (1997), which went on to beat all box office records held before then, as, at the time, Титаник (1997) became the highest grossing movie of all time, and cemented DiCaprio''s reputation as a teen heartthrob. Following his work on Титаник (1997), DiCaprio kept a low profile for a number of years, with roles in Челoвек в железной маске (1998) and the low-budget Пляж (2000) being some of his few notable roles during this period.

In 2002, he burst back into screens throughout the world with leading roles in Поймай меня, если сможешь (2002) and Банды Нью-Йорка (2002), his first of many collaborations with director Martin Scorsese. With a current salary of $20 million a movie, DiCaprio is now one of the biggest movie stars in the world. However, he has not limited his professional career to just acting in movies, as DiCaprio is a committed environmentalist, who is actively involved in many environmental causes, and his commitment to this issue led to his involvement in The 11th Hour, a documentary movie about the state of the natural environment. As someone who has gone from small roles in television commercials to one of the most respected actors in the world, DiCaprio has had one of the most diverse careers in cinema. DiCaprio continued to defy conventions about the types of roles he would accept, and with his career now seeing him leading all-star casts in action thrillers such as Отступники (2006), Остров проклятых (2010) and Christopher Nolan''s Начало (2010), DiCaprio continues to wow audiences by refusing to conform to any cliché about actors.

In 2012, he played a mustache twirling villain in Джанго освобожденный (2012), and then tragic literary character Jay Gatsby in Великий Гэтсби (2013) and Jordan Belfort in Волк с Уолл-стрит (2013).

DiCaprio is passionate about environmental and humanitarian causes, having donated $1,000,000 to earthquake relief efforts in 2010, the same year he contributed $1,000,000 to the Wildlife Conservation Society.','Leonardo ','MALE','https://cdn.britannica.com/65/227665-050-D74A477E/American-actor-Leonardo-DiCaprio-2016.jpg','DiCaprio');
insert into actors values (default, '2023-05-09', '2023-05-09', true, 42,'Joseph Leonard Gordon-Levitt was born February 17, 1981 in Los Angeles, California, to Jane Gordon and Dennis Levitt. Joseph was raised in a Jewish family with his late older brother, Dan Gordon-Levitt, who passed away in October 2010. His parents worked for the Pacifica Radio station KPFK-FM and his maternal grandfather, Michael Gordon, had been a well-known movie director. Joseph first became well known for his starring role on NBC''s award-winning comedy series Третья планета от Солнца (1996). During his six seasons on the show, he won two YoungStar Awards and also shared in three Screen Actors Guild Award® nominations for Outstanding Performance by a Comedy Series Ensemble.
','Joseph  ','MALE','https://upload.wikimedia.org/wikipedia/commons/7/7d/Joseph_Gordon-Levitt_2013.jpg','Gordon-Levitt');
insert into actors values (default, '2023-05-09', '2023-05-09', true, 49,'Christian Charles Philip Bale was born in Pembrokeshire, Wales, UK on January 30, 1974, to English parents Jennifer "Jenny" (James) and David Bale. His mother was a circus performer and his father, who was born in South Africa, was a commercial pilot. The family lived in different countries throughout Bale''s childhood, including England, Portugal, and the United States. Bale acknowledges the constant change was one of the influences on his career choice.

His first acting job was a cereal commercial in 1983; amazingly, the next year, he debuted on the West End stage in "The Nerd". A role in the 1986 NBC mini-series Анастасия: Тайна Анны (1986) caught Steven Spielberg''s eye, leading to Bale''s well-documented role in Империя Солнца (1987). For the range of emotions he displayed as the star of the war epic, he earned a special award by the National Board of Review for Best Performance by a Juvenile Actor.

','Christian  ','MALE','https://i0.wp.com/www.uselessdaily.com/wp-content/uploads/2016/01/christian-bale-photos-4.jpg?fit=1280%2C960&ssl=1','Bale');
insert into actors values (default, '2023-05-09', '2023-05-09', true, 54,'Hugh Michael Jackman is an Australian actor, singer, multi-instrumentalist, dancer and producer. Jackman has won international recognition for his roles in major films, notably as superhero, period, and romance characters. He is best known for his long-running role as Wolverine in the X-Men film series, as well as for his lead roles in the romantic-comedy fantasy Kate & Leopold (2001), the action-horror film Van Helsing (2004), the drama The Prestige and The Fountain (2006), the epic historical romantic drama Australia (2008), the film version of Les Misérables (2012), and the thriller Prisoners (2013). His work in Les Misérables earned him his first Academy Award nomination for Best Actor and his first Golden Globe Award for Best Actor - Motion Picture Musical or Comedy in 2013. In Broadway theatre, Jackman won a Tony Award for his role in The Boy from Oz. A four-time host of the Tony Awards themselves, he won an Emmy Award for one of these appearances. Jackman also hosted the 81st Academy Awards on 22 February 2009.

Jackman was born in Sydney, New South Wales, to Grace McNeil (Greenwood) and Christopher John Jackman, an accountant. He is the youngest of five children. His parents, both English, moved to Australia shortly before his birth. He also has Greek (from a great-grandfather) and Scottish (from a grandmother) ancestry.

','Hugh ','MALE','https://i0.wp.com/short-biography.com/wp-content/uploads/hugh-jackman/HJ.jpg?ssl=1','Jackman');
insert into actors values (default, '2023-05-09', '2023-05-09', true, 38,'Scarlett Ingrid Johansson was born on November 22, 1984 in Manhattan, New York City, New York. Her mother, Melanie Sloan is from a Jewish family from the Bronx and her father, Karsten Johansson is a Danish-born architect from Copenhagen. She has a sister, Vanessa Johansson, who is also an actress, a brother, Adrian, a twin brother, Hunter Johansson, born three minutes after her, and a paternal half-brother, Christian. Her grandfather was writer Ejner Johansson.

','Scarlett  ','FEMALE','https://m.media-amazon.com/images/M/MV5BMTM3OTUwMDYwNl5BMl5BanBnXkFtZTcwNTUyNzc3Nw@@._V1_.jpg','Johansson');
insert into actors values (default, '2023-05-09', '2023-05-09', true, 28,'When hunky, twenty-year-old heart-throb Heath Ledger first came to the attention of the public in 1999, it was all too easy to tag him as a "pretty boy" and an actor of little depth. He spent several years trying desperately to sway this image, but this was a double-edged sword. His work comprised nineteen films, including 10 причин моей ненависти (1999), Патриот (2000), История рыцаря (2001), Бал монстров (2001), Банда Келли (2003), Братья Гримм (2005), Короли Догтауна (2005), Горбатая гора (2005), Казанова (2005), Кэнди (2006), Меня там нет (2007), Темный рыцарь (2008) and Воображариум доктора Парнасса (2009). He also produced and directed music videos and aspired to be a film director.

Heath Ledger was born on the fourth of April 1979, in Perth, Western Australia, to Sally (Ramshaw), a teacher of French, and Kim Ledger, a mining engineer who also raced cars. His ancestry was Scottish, English, Irish, and Sephardi Jewish. As the story goes, in junior high school it was compulsory to take one of two electives, either cooking or drama. As Heath could not see himself in a cooking class he tried his hand at drama. Heath was talented, however the rest of the class did not acknowledge his talent. When he was seventeen he and a friend decided to pack up, leave school, take a car and rough it to Sydney. Heath believed Sydney to be the place where dreams were made or, at least, where actors could possibly get their big break. Upon arriving in Sydney with a purported sixty-nine cents to his name, Heath tried everything to get a break.

','Heath','MALE','https://upload.wikimedia.org/wikipedia/commons/e/ea/Heath_Ledger_%282%29.jpg','Ledger');
insert into actors values (default, '2023-05-09', '2023-05-09', true, 85,'With an authoritative voice and calm demeanor, this ever popular American actor has grown into one of the most respected figures in modern US cinema. Morgan was born on June 1, 1937 in Memphis, Tennessee, to Mayme Edna (Revere), a teacher, and Morgan Porterfield Freeman, a barber. The young Freeman attended Los Angeles City College before serving several years in the US Air Force as a mechanic between 1955 and 1959. His first dramatic arts exposure was on the stage including appearing in an all-African American production of the exuberant musical Hello, Dolly!.

Throughout the 1970s, he continued his work on stage, winning Drama Desk and Clarence Derwent Awards and receiving a Tony Award nomination for his performance in The Mighty Gents in 1978. In 1980, he won two Obie Awards, for his portrayal of Shakespearean anti-hero Coriolanus at the New York Shakespeare Festival and for his work in Mother Courage and Her Children. Freeman won another Obie in 1984 for his performance as The Messenger in the acclaimed Brooklyn Academy of Music production of Lee Breuer''s The Gospel at Colonus and, in 1985, won the Drama-Logue Award for the same role. In 1987, Freeman created the role of Hoke Coleburn in Alfred Uhry''s Pulitzer Prize-winning play Driving Miss Daisy, which brought him his fourth Obie Award. In 1990, Freeman starred as Petruchio in the New York Shakespeare Festival''s The Taming of the Shrew, opposite Tracey Ullman. Returning to the Broadway stage in 2008, Freeman starred with Frances McDormand and Peter Gallagher in Clifford Odets'' drama The Country Girl, directed by Mike Nichols.

','Morgan ','MALE','https://m.media-amazon.com/images/M/MV5BMTc0MDMyMzI2OF5BMl5BanBnXkFtZTcwMzM2OTk1MQ@@._V1_FMjpg_UX1000_.jpg','Freeman');
insert into actors values (default, '2023-05-09', '2023-05-09', true, 46,'Striking Irish actor Cillian Murphy was born in Douglas, the oldest child of Brendan Murphy, who works for the Irish Department of Education, and a mother who is a teacher of French. He has three younger siblings. Murphy was educated at Presentation Brothers College, Cork. He went on to study law at University College Cork, but dropped out after about a year. During this time Murphy also pursued an interest in music, playing guitar in various bands. Upon leaving University, Murphy joined the Corcadorca Theater Company in Cork, and played the lead role in "Disco Pigs", amongst other plays.

Various film roles followed, including a film adaptation of Дискосвиньи (2001). However, his big film break came when he was cast in Danny Boyle''s 28 дней спустя (2002), which became a surprise international hit. This performance earned him nominations for Best Newcomer at the Empire Awards and Breakthrough Male Performance at the MTV Movie Awards.

','Cillian','MALE','https://flxt.tmsimg.com/assets/236083_v9_bb.jpg','Murphy');
insert into actors values (default, '2023-05-09', '2023-05-09', true, 69,'John Joseph Travolta was born in Englewood, New Jersey, one of six children of Helen Travolta (née Helen Cecilia Burke) and Salvatore/Samuel J. Travolta. His father was of Italian descent and his mother was of Irish ancestry. His father owned a tire repair shop called Travolta Tires in Hillsdale, NJ. Travolta started acting appearing in a local production of "Who''ll Save the Plowboy?". His mother, herself an actress and dancer, enrolled him in a drama school in New York, where he studied voice, dancing and acting. He decided to combine all three of these skills and become a musical comedy performer. At 16 he landed his first professional job in a summer stock production of the musical "Bye Bye Birdie". He quit school at 16 and moved to New York, and worked regularly in summer stock and on television commercials. When work became scarce in New York, he went to Hollywood and appeared in minor roles in several series. A role in the national touring company of the hit 1950s musical "Grease" brought him back to New York. An opening in the New York production of "Grease" gave him his first Broadway role at age 18. After "Grease", he became a member of the company of the Broadway show "Over Here", which starred The Andrews Sisters. After ten months in "Over Here", he decided to try Hollywood once again. Once back in Hollywood, he had little trouble getting roles in numerous television shows. He was seen on Новобранцы (1972), Критическое положение! (1972) and Медицинский центр (1969) and also made a movie, Адский дождь (1975), which was shot in New Mexico. The day he returned to Hollywood from New Mexico, he was called to an audition for a new situation comedy series ABC was planning to produce called Добро пожаловать назад, Коттер (1975). He got the part of Vinnie Barbarino and the series went on the air during the 1975 fall season.

','John','MALE','https://m.media-amazon.com/images/M/MV5BMTMyMjZlYzgtZWRjMC00OTRmLTllZTktMmM1ODVmNjljMTQyXkEyXkFqcGdeQXVyMTExNzQ3MzAw._V1_.jpg','Travolta');
insert into actors values (default, '2023-05-09', '2023-05-09', true, 53,'Uma Karuna Thurman was born in Boston, Massachusetts, into a highly unorthodox and internationally-minded family. She is the daughter of Nena Thurman (née Birgitte Caroline von Schlebrügge), a fashion model and socialite who now runs a mountain retreat, and of Robert Thurman (Robert Alexander Farrar Thurman), a professor and academic who is one of the nation''s foremost Buddhist scholars. Uma''s mother was born in Mexico City, Mexico, to a German father and a Swedish mother (who herself was of Swedish, Danish, and German descent). Uma''s father, a New Yorker, has English, Scots-Irish, Scottish, and German ancestry. Uma grew up in Amherst, Massachusetts, where her father worked at Amherst College.

','Uma','FEMALE','https://m.media-amazon.com/images/M/MV5BMjMxNzk1MTQyMl5BMl5BanBnXkFtZTgwMDIzMDEyMTE@._V1_.jpg','Thurman');
insert into actors values (default, '2023-05-09', '2023-05-09', true, 75,'Samuel L. Jackson is an American producer and highly prolific actor, having appeared in over 100 films, including Крепкий орешек 3: Возмездие (1995), Неуязвимый (2000), Детектив Шафт (2000), Формула 51 (2001), Стон черной змеи (2006), Змеиный полет (2006), and the Star Wars prequel trilogy (1999-2005), as well as the Marvel Cinematic Universe.

Samuel Leroy Jackson was born in Washington, D.C., to Elizabeth (Montgomery) and Roy Henry Jackson. He was raised by his mother, a factory worker, and his grandparents. At Morehouse College, Jackson was active in the black student movement. In the seventies, he joined the Negro Ensemble Company (together with Morgan Freeman). In the eighties, he became well-known after three movies made by Spike Lee: Делай как надо (1989), Блюз о лучшей жизни (1990) and Лихорадка джунглей (1991). He achieved prominence and critical acclaim in the early 1990s with films such as Игры патриотов (1992), Эмос и Эндрю (1993), Настоящая любовь (1993), Парк юрского периода (1993), and his collaborations with director Quentin Tarantino, including Криминальное чтиво (1994), Джеки Браун (1997), and later Джанго освобожденный (2012). Going from supporting player to leading man, his performance in Криминальное чтиво (1994) gave him an Oscar nomination for his character Jules Winnfield, and he received a Silver Berlin Bear for his part as Ordell Robbi in Джеки Браун (1997). Jackson usually played bad guys and drug addicts before becoming an action hero, co-starring with Bruce Willis in Крепкий орешек 3: Возмездие (1995) and Geena Davis in Долгий поцелуй на ночь (1996).

','Samuel','MALE','https://m.media-amazon.com/images/M/MV5BMTQ1NTQwMTYxNl5BMl5BanBnXkFtZTYwMjA1MzY1._V1_FMjpg_UX1000_.jpg','Jackson');
insert into actors values (default, '2023-05-09', '2023-05-09', true, 61,'Often mistaken for an American because of his skill at imitating accents, actor Tim Roth was born Timothy Simon Roth on May 14, 1961 in Lambeth, London, England. His mother, Ann, was a teacher and landscape painter. His father, Ernie, was a journalist who had changed the family name from "Smith" to "Roth"; Ernie was born in Brooklyn, New York, to an immigrant family of Irish ancestry.

Tim grew up in Dulwich, a middle-class area in the south of London. He demonstrated his talent for picking up accents at an early age when he attended school in Brixton, where he faced persecution from classmates for his comfortable background and quickly perfected a cockney accent to blend in. He attended Camberwell Art College and studied sculpture before he dropped out and pursued acting.

','Timothy','MALE','https://www.themoviedb.org/t/p/w500/qSizF2i9gz6c6DbAC5RoIq8sVqX.jpg','Roth');
insert into actors values (default, '2023-05-09', '2023-05-09', true, 60,'William Bradley "Brad" Pitt was born on December 18, 1963 in Shawnee, Oklahoma and raised in Springfield, Missouri to Jane Etta Pitt (née Hillhouse), a school counselor & William Alvin "Bill" Pitt, a truck company manager. At Kickapoo High School, Pitt was involved in sports, debating, student government and school musicals. Pitt attended the University of Missouri, where he majored in journalism with a focus on advertising. He occasionally acted in fraternity shows. He left college two credits short of graduating to move to California. Before he became successful at acting, Pitt supported himself by driving strippers in limos, moving refrigerators and dressing as a giant chicken while working for El Pollo Loco.

','Bred','MALE','https://images.mubicdn.net/images/cast_member/2552/cache-207-1524922850/image-w856.jpg?size=800x','Pitt');
insert into actors values (default, '2023-05-09', '2023-05-09', true, 66,'Christoph Waltz is an Austrian-German actor. He is known for his work with American filmmaker Quentin Tarantino, receiving acclaim for portraying SS-Standartenführer Hans Landa in Бесславные ублюдки (2009) and bounty hunter Dr. King Schultz in Джанго освобожденный (2012). For each performance, he won an Academy Award, a BAFTA Award, and a Golden Globe Award for Best Supporting Actor. Additionally, he received the Best Actor Award at the Cannes Film Festival and a Screen Actors Guild Award for his portrayal of Landa.

Christoph Waltz was born in Vienna, Austria, into a theatrical family, his mother Elisabeth Urbancic, an Austrian-born costume designer, and Johannes Waltz, a German-born stage builder. He has three siblings. His maternal grandmother was Viennese Burgtheater actress Maria Mayen, and his step-grandfather was fellow Burgtheater actor Emmerich Reimers. His maternal grandfather, Rudolf von Urban, was a psychologist and psychiatrist who wrote the 1949 book "Sex Perfection and Marital Happiness".

','Christoph','MALE','https://upload.wikimedia.org/wikipedia/commons/d/d8/Christoph_Waltz_Viennale_2017_f_%28cropped%29.jpg','Waltz');
insert into actors values (default, '2023-05-09', '2023-05-09', true, 55,'Jamie Foxx is an American actor, singer and comedian. He won an Academy Award for Best Actor, BAFTA Award for Best Actor in a Leading Role, and Golden Globe Award for Best Actor in a Musical or Comedy, for his work in the biographical film Рэй (2004). The same year, he was nominated for the Academy Award for Best Supporting Actor for his role in the action film Соучастник (2004). Other prominent acting roles include the title role in the film Джанго освобожденный (2012), the supervillain Electro in Новый Человек-паук: Высокое напряжение (2014), and William Stacks in the modern version of Энни (2014).


','Jamie','MALE','https://people.com/thmb/aY_L557npgHVQvUSeKxrKdeFdOs=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():focal(674x19:676x21)/jamie-foxx-041323-37d6db2981fb4ce8bfca39216680dd18.jpg','Foxx');
insert into actors values (default, '2023-05-09', '2023-05-09', true, 72,'Kurt Vogel Russell was born on March 17, 1951 in Springfield, Massachusetts and raised in Thousand Oaks, California to Louise Julia Russell (née Crone), a dancer & Bing Russell, an actor. He is of English, German, Scottish and Irish descent. His first roles were as a child on television series, including a lead role on the Western series Путешествие Джейме МакФитерза (1963). Russell landed a role in the Elvis Presley movie, Это случилось на Всемирной ярмарке (1963), when he was eleven years old. Walt Disney himself signed Russell to a 10-year contract, and, according to Robert Osborne, he became the studio''s top star of the 1970s. Having voiced adult Copper in the animated Disney film Лис и пёс (1981), Russell is one of the few famous child stars in Hollywood who has been able to continue his acting career past his teen years.


','Kurt','MALE','https://cdn.centraljersey.com/wp-content/uploads/sites/26/2021/11/ReMINDKurtRuss.jpg','Russell');
insert into actors values (default, '2023-05-09', '2023-05-09', true, 53,'American actor, filmmaker and activist Edward Harrison Norton was born on August 18, 1969, in Boston, Massachusetts, and was raised in Columbia, Maryland.

His mother, Lydia Robinson "Robin" (Rouse), was a foundation executive and teacher of English, and a daughter of famed real estate developer James Rouse, who developed Columbia, MD; she passed away of brain cancer on March 6, 1997. His father, Edward Mower Norton, was an environmental lawyer and conservationist, who works for the National Trust for Historic Preservation. Edward has two younger siblings, James and Molly.


','Edward','MALE','https://m.media-amazon.com/images/M/MV5BMTYwNjQ5MTI1NF5BMl5BanBnXkFtZTcwMzU5MTI2Mw@@._V1_FMjpg_UX1000_.jpg','Norton');
insert into actors values (default, '2023-05-09', '2023-05-09', true, 50,'Benjamin Géza "Ben" Affleck-Boldt was born on August 15, 1972 in Berkeley, California and raised in Cambridge, Massachusetts, to mother Chris Anne (Boldt), a school teacher, and father Timothy Byers "Tim" Affleck, a social worker. Ben has a younger brother, actor Casey Affleck, who was born in 1975. He is of mostly English, Irish, German, and Scottish ancestry. His middle name, Géza, is after a Hungarian family friend who was a Holocaust survivor.


','Ben','MALE','https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Ben_Affleck_by_Gage_Skidmore_3.jpg/640px-Ben_Affleck_by_Gage_Skidmore_3.jpg','Affleck');
insert into actors values (default, '2023-05-09', '2023-05-09', true, 44,'Born in 1979 in London, England, actress Rosamund Mary Elizabeth Pike is the only child of a classical violinist mother, Caroline (Friend), and an opera singer father, Julian Pike. Due to her parents'' work, she spent her early childhood traveling around Europe. Pike attended Badminton School in Bristol, England and began acting at the National Youth Theatre. While appearing in a National Youth Theatre production of "Romeo and Juliet", she was first spotted and signed by an agent, although she continued her education at Wadham College, Oxford, where she read English Literature, eventually graduating with an upper second class honors degree.


','Rosamund','FEMALE','https://m.media-amazon.com/images/M/MV5BNDQ5MDIyMjg3NV5BMl5BanBnXkFtZTgwOTU2NTE0NDM@._V1_.jpg','Pike');
insert into actors values (default, '2023-05-09', '2023-05-09', true, 50,'A tall, strikingly attractive blue-eyed natural blonde, Cameron Diaz was born in 1972 in San Diego, the daughter of a Cuban-American father and a German mother. Self described as "adventurous, independent and a tough kid," Cameron left home at 16 and for the next 5 years lived in such varied locales as Japan, Australia, Mexico, Morocco, and Paris. Returning to California at the age of 21, she was working as a model when she auditioned for a big part in Маска (1994). To her amazement and despite having no previous acting experience, she was cast as the female lead in the film opposite Jim Carrey. Over the next 3 years, she honed her acting skills in such low budget independent films as Последний ужин (1995); Чувствуя Миннесоту (1996); and Как удержаться на плаву (1996). She returned to main stream films in Свадьба лучшего друга (1997), in which she held her own against veteran actress Julia Roberts. She earned full fledged star status in 1998 for her performance in the box office smash Все без ума от Мэри (1998). With her name near the top on virtually every list of Hollyood''s sexiest actresses, and firmly established as one of filmdom''s hottest properties and most sought after actresses, Cameron Diaz appears to possess everything necessary to become one of the super stars of the new century.


','Cameron','FEMALE','https://mindmaps.aginganalytics.com/storage/faces/Cameron%20Diaz%20new.jpg','Diaz');
insert into actors values (default, '2023-05-09', '2023-05-09', true, 52,'Matthew Paige Damon was born on October 8, 1970, in Boston, Massachusetts, to Kent Damon, a stockbroker, realtor and tax preparer, and Nancy Carlsson-Paige, an early childhood education professor at Lesley University. Matt has an older brother, Kyle, a sculptor. His father was of English and Scottish descent, and his mother is of Finnish and Swedish ancestry. The family lived in Newton until his parents divorced in 1973, when Damon and his brother moved with his mother to Cambridge. He grew up in a stable community, and was raised near actor Ben Affleck.


','Matt','MALE','https://m.media-amazon.com/images/M/MV5BMTM0NzYzNDgxMl5BMl5BanBnXkFtZTcwMDg2MTMyMw@@._V1_.jpg','Damon');
insert into actors values (default, '2023-05-09', '2023-05-09', true, 55,'Award-winning actor Mark Ruffalo was born on November 22, 1967, in Kenosha, Wisconsin, of humble means to father Frank Lawrence Ruffalo, a construction painter and Marie Rose (Hebert), a stylist and hairdresser; his father''s ancestry is Italian and his mother is of half French-Canadian and half Italian descent. Mark moved with his family to Virginia Beach, Virginia, where he lived out most of his teenage years. Following high school, Mark moved with his family to San Diego and soon migrated north, eventually settling in Los Angeles.

Mark first took classes at the Stella Adler Conservatory and subsequently co-founded the Orpheus Theatre Company, an Equity-Waiver establishment, where he worked in nearly every capacity. From acting, writing, directing and producing to running the lights and building sets while building his resume.


','Mark','MALE','https://cdn.britannica.com/97/219497-050-B1B58B0F/Mark-Ruffalo-2018.jpg','Ruffalo');

# actors to movie ---------------------------------->
insert into actor_movie values (1,1);
insert into actor_movie values (2,1);
insert into actor_movie values (3,2);
insert into actor_movie values (4,2);
insert into actor_movie values (5,3);
insert into actor_movie values (6,3);
insert into actor_movie values (7,4);
insert into actor_movie values (8,4);
insert into actor_movie values (9,5);
insert into actor_movie values (10,5);
insert into actor_movie values (11,5);
insert into actor_movie values (12,6);
insert into actor_movie values (9,6);
insert into actor_movie values (13,6);
insert into actor_movie values (14,6);
insert into actor_movie values (14,4);
insert into actor_movie values (15,7);
insert into actor_movie values (16,7);
insert into actor_movie values (17,7);
insert into actor_movie values (18,7);
insert into actor_movie values (19,8);
insert into actor_movie values (20,8);
insert into actor_movie values (21,9);
insert into actor_movie values (7,9);
insert into actor_movie values (17,9);
insert into actor_movie values (20,9);
insert into actor_movie values (23,10);
insert into actor_movie values (17,10);
insert into actor_movie values (18,10);
insert into actor_movie values (13,11);
insert into actor_movie values (19,11);
insert into actor_movie values (22,12);
insert into actor_movie values (19,12);
insert into actor_movie values (24,13);
insert into actor_movie values (25,13);
insert into actor_movie values (26,14);
insert into actor_movie values (7,14);
insert into actor_movie values (27,15);
insert into actor_movie values (7,15);
insert into actor_movie values (28,16);
insert into actor_movie values (7,16);
insert into actor_movie values (7,17);
insert into actor_movie values (3,17);
insert into actor_movie values (5,17);
# genres  ---------------------------------->
insert into genres values (1, '2023-05-09', '2023-05-09', true,'action','/images/action.jpg');
insert into genres values (2, '2023-05-09', '2023-05-09', true,'adventure','/images/adventure.jpg');
insert into genres values (3, '2023-05-09', '2023-05-09', true,'comedy','/images/comedy.jpg');
insert into genres values (4, '2023-05-09', '2023-05-09', true,'drama','/images/drama.jpg');
insert into genres values (5, '2023-05-09', '2023-05-09', true,'sci-fi','/images/sci-fi.jpg');
insert into genres values (6, '2023-05-09', '2023-05-09', true,'mystery','/images/mystery.jpg');
insert into genres values (7, '2023-05-09', '2023-05-09', true,'crime','/images/crime.jpg');
insert into genres values (8, '2023-05-09', '2023-05-09', true,'war','/images/war.jpg');
insert into genres values (9, '2023-05-09', '2023-05-09', true,'western','/images/western.jpg');
insert into genres values (10, '2023-05-09', '2023-05-09', true,'thriller','/images/thriller.jpg');
insert into genres values (11, '2023-05-09', '2023-05-09', true,'horror','/images/horror.jpg');
insert into genres values (12, '2023-05-09', '2023-05-09', true,'fantasy','/images/fantasy.jpg');

# genre to movie ---------------------------------->
insert into genre_movie values (1,1);
insert into genre_movie values (2,1);
insert into genre_movie values (3,1);
insert into genre_movie values (1,2);
insert into genre_movie values (2,2);
insert into genre_movie values (3,2);
insert into genre_movie values (2,3);
insert into genre_movie values (4,3);
insert into genre_movie values (5,3);
insert into genre_movie values (1,4);
insert into genre_movie values (2,4);
insert into genre_movie values (5,4);
insert into genre_movie values (4,5);
insert into genre_movie values (5,5);
insert into genre_movie values (6,5);
insert into genre_movie values (1,6);
insert into genre_movie values (7,6);
insert into genre_movie values (4,6);
insert into genre_movie values (7,7);
insert into genre_movie values (4,7);
insert into genre_movie values (4,8);
insert into genre_movie values (2,8);
insert into genre_movie values (8,8);
insert into genre_movie values (4,9);
insert into genre_movie values (9,9);
insert into genre_movie values (7,10);
insert into genre_movie values (4,10);
insert into genre_movie values (9,10);
insert into genre_movie values (7,11);
insert into genre_movie values (4,11);
insert into genre_movie values (6,11);
insert into genre_movie values (4,12);
insert into genre_movie values (6,12);
insert into genre_movie values (6,13);
insert into genre_movie values (4,13);
insert into genre_movie values (10,13);
insert into genre_movie values (4,14);
insert into genre_movie values (7,14);
insert into genre_movie values (10,15);
insert into genre_movie values (4,15);
insert into genre_movie values (7,15);
insert into genre_movie values (10,16);
insert into genre_movie values (4,16);
insert into genre_movie values (6,16);
insert into genre_movie values (3,17);
insert into genre_movie values (7,17);